# @package _group_
# name of default target
default_compute_target: 'jialeichen1' #"cpu-cluster"
# where intermediary output is written
compliant_datastore: "workspaceblobstore"

# Linux targets
linux_cpu_dc_target: 'jialeichen1' #"cpu-cluster"
linux_cpu_prod_target: 'jialeichen1' #"cpu-cluster"
linux_gpu_dc_target: 'jialeichen2' #"gpu-nc12-lowpri"
linux_gpu_prod_target: 'jialeichen2' #"gpu-nc12-lowpri"

# data I/O for linux modules
linux_input_mode: "mount"
linux_output_mode: "mount"

# Windows targets
windows_cpu_prod_target: "cpu-win"
windows_cpu_dc_target: "cpu-win"

# data I/O for windows modules
windows_input_mode: "download"
windows_output_mode: "upload"

# hdi cluster
hdi_prod_target: "hdi-cluster"
